print("¿Qué sale de la cruza entre un mono y un pato?", end="")
input()
print("¡Un monopatín!" +
      "¿Porqué vuelan los pájaros pa'l sur?", sep="\n", end="")
input()
print("¡Porque caminando tardarían muchísimo!")
print("¿En qué se parecen una familia, un bombero y un barco?", end="")
input()
print("No sé... ¿en qué se parecen?", end="")
input()
print("En que el bombero y el barco tienen casco.")
print("¿Y la familia?", "-Bien, gracias.")
